apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-svc
spec:
  selector:
    matchLabels:
      app: identity-svc
  template:
    metadata:
      labels:
        app: identity-svc
    spec:
      containers:
        - name: identity-svc
          image: quay.io/keycloak/keycloak:latest
          imagePullPolicy: IfNotPresent
          args: ["start-dev"]
          env:
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: kc_db_url
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: kc_db_username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: kc_db_password
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: kc_bootstrap_admin_username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: kc_bootstrap_admin_password
          envFrom:
            - configMapRef:
                name: identity-svc-config
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: identity-svc
  ports:
    - port: 80
      targetPort: 8080
